### ISSUE TITLE
suggestion include fix modification in PEPTIDE sequence

### ISSUE THREAD

**Issue by ATPs** [UWPR/Comet#58] opened 2024-05-27 02:15 UTC
Hi, Jimmy~
for fixed modification, is it possible to also show it in the peptide sequence?
for example, peptide `-.LCYVALDFEQ[0.9840]EMATAASSSSLEK.-`.  C with a fixed modificaton. if the sequence is `-.LC[57.02]YVALDFEQ[0.9840]EMATAASSSSLEK.-` , it is possible to calculate the mz from the sequence directly.
Not urgent, but it might be helpful.

Thank you!

**Comment by jke000** [comment] 2024-05-27 03:01
Sure, I can implement a search parameter that you can set, some thing like "annotate_static_mods = 1", which will print out the static/fixed modification masses in the peptide sequence.  It's easy to do; I'll follow-up here once it's available.

**Comment by ATPs** [comment] 2024-05-27 04:13
sure. Thank you, Jimmy.

**Comment by jke000** [comment] 2024-05-30 19:55
As I go implement this now, I just want to confirm that you're only interested in this functionality for the .txt output.  Is that correct?  There is a "modified_peptide" attribute in the pep.xml output that also reports modified masses but there's no significant digits for the masses in that peptide string.  And there are other elements that detail the modification masses so it doesn't seem to make sense to add this functionality to the pep.xml output (but I will if that would be useful for you).

**Comment by ATPs** [comment] 2024-05-31 00:40
hi, Jimmy. I found this when I am trying to use ms2rescore. it cannot parse the .pin file generated by comet so I have to do some conversion. Adding this option to the text output is good to me. So we can calculate the molecular weight and get the modifications from the peptide sequence directly. I think pep.xml already included mw so it is not necessary to include it. Best wishes!

**Comment by jke000** [comment] 2024-05-31 00:49
Do you by chance know what the issue is with ms2rescore in Comet's pin file?  Is it a particular column that's the issue?

The text already includes the calculated MW of the modified peptide as well.  It's the 4th column with the column header "calc_neutral_mass".  Any reason why you can't use the existing calculated MW?

**Comment by ATPs** [comment] 2024-05-31 01:08
oh, ms2rescore recognize peptide modifications in form of PEP[unimod:4]TIDE or PEPTIDE[oxidation]. so we need to change the [+57] to modification name. Ms2rescore uses the sequence to predict retention time and ms2 spectrum. It took me a while to found the fixed modification was not included in the peptide column of the .pin file. so I think it might be better to include this modification so that the sequence matches the MW. 
It is not a urgent thing since I know I need to consider this when doing the conversion. 
not sure, but if we can input the unimod ID somewhere it might increase the compatibility to tools like ms2rescore.

thank you. Best wishes!
xiaolong

**Comment by jke000** [comment] 2024-05-31 23:55
Xiaolong,

I just downloaded and tried to run MS2Rescore myself using Comet results.  I gave it both pep.xml and mzid files as input and I couldn't get either to work.  So I just [posted an issue](https://github.com/compomics/ms2rescore/issues/152) on that tool's project page and hopefully the developer will respond with some positive news.

**Comment by ATPs** [comment] 2024-06-01 14:01
sure. Thank you, Jimmy.

I found it is because they cannot handle peptide sequence with only mass difference annotation, like PEP[+57]TIDE. format like PEP[unimod:4]TIDE or PEPTIDE[oxidation] will work.

I guess it is because ms2rescore used tools to predict retention time and ms/ms spectrum of peptide, and these tools might need the molecular composition of the peptide sequence. currently, comet allows the input of mass difference for amino acid modifications, but did not include the modification name or atomic composition.

 add additional optional field in the modification setting to put the modification name or molecular composition like (CH3)?

Just my suggestion. 
Best wishes!

**Comment by jke000** [comment] 2024-07-10 18:19
I'm going to close this issue.  The CompOmics team has [implemented a fix](https://github.com/compomics/psm_utils/pull/87) to support Comet's pepXML output by MS2Resore.  You'll need to wait for them to create another Release of that tool which incorporates this fix in order to run their tool on Comet output.

**Closed by jke000** 2024-07-10 18:19 UTC

**Comment by ATPs** [comment] 2024-07-11 00:00
Sure. Thank you!
Best😃

**Comment by jke000** [comment] 2024-07-17 16:29
Just as an update, the compomics developers just release v0.9.1 of psm_utils (and by extension ms2rescore) which fixes support for Comet's pepXML and mzIdentML files.
